images: test.csv
evaluate: True
output_folder: inference
model:
  path: /workspace/recognizer-training-pipeline/weights_test/
  type: extended
  num_class: 37
  lstm_layers: 2
  is_lstm_bidirectional: True
  classification_regions: ["dubai", "abu-dhabi", "sharjah", "ajman", "ras-al-khaimah", "fujairah", "alquwain", "bahrein", "oman", "saudi", "quatar", "kuwait", "others"]
use_gpu: True
transforms: no_transform
threshold: 0.7
alphabet: string.digits+string.ascii_lowercase
image_w: 160
image_h: 64
