global:
  experiment_name: uae
  run_name: cc_2k
  run_id: 7087c163f9b549cebd07d2bb581b829b
  distributed: True
  epochs: 100
  checkpoint: /workspace/recognizer-training-pipeline/weights_test
  gpu: 1
  alphabet: string.digits+string.ascii_lowercase

model:
  type: extended
  num_class: 37
  lstm_layers: 2
  is_lstm_bidirectional: True
  classification_regions: ["dubai", "abu-dhabi", "sharjah", "ajman", "ras-al-khaimah", "fujairah", "alquwain", "bahrein", "oman", "saudi", "quatar", "kuwait", "others"] # leave empty(not []) for no class

optimizer:
  lr: 0.0001

scheduler:
  mode: min
  patience: 5
  factor: 0.1
  min_lr: 1e-6

train_data:
  csv_files: ['/workspace/pycharm_project_769/train_26.12.24.csv']
  transform: transform_old
  image_w: 160
  image_h: 64

val_data:
  csv_files: ['/workspace/pycharm_project_769/test_26.12.24.csv']
  transform: no_transform
  image_w: 160
  image_h: 64

loader:
  batch_size: 256
  num_workers: 64
  pin_memory: True
  drop_last: True
